# -*- coding: utf-8 -*-
# Auto-generated by schemapi: do not modify file directly
# - schemapi version: 0.3.0
# - date:    2018-01-25 00:15:25

from .schema import Root














from .schema import AggregateOp
from .schema import AggregateTransform
from .schema import AggregatedFieldDef
from .schema import Anchor
from .schema import AndFilter
from .schema import AutoSizeParams
from .schema import AutosizeType
from .schema import Axis
from .schema import AxisConfig
from .schema import AxisOrient
from .schema import AxisResolveMap
from .schema import BarConfig
from .schema import BinParams
from .schema import BinTransform
from .schema import BrushConfig
from .schema import CalculateTransform
from .schema import CompositeUnitSpec
from .schema import CompositeUnitSpecAlias
from .schema import Conditional_MarkPropFieldDef
from .schema import Conditional_TextFieldDef
from .schema import Conditional_ValueDef
from .schema import Config
from .schema import CsvDataFormat
from .schema import Data
from .schema import DataFormat
from .schema import DateTime
from .schema import Encoding
from .schema import EncodingWithFacet
from .schema import EqualFilter
from .schema import FacetFieldDef
from .schema import FacetMapping
from .schema import FacetSpec
from .schema import FacetedCompositeUnitSpecAlias
from .schema import FieldDef
from .schema import FilterTransform
from .schema import FontStyle
from .schema import FontWeight
from .schema import HConcatSpec
from .schema import Header
from .schema import HorizontalAlign
from .schema import InlineData
from .schema import Interpolate
from .schema import InterpolateParams
from .schema import IntervalSelection
from .schema import IntervalSelectionConfig
from .schema import JsonDataFormat
from .schema import LayerSpec
from .schema import Legend
from .schema import LegendConfig
from .schema import LegendOrient
from .schema import LegendResolveMap
from .schema import LocalMultiTimeUnit
from .schema import LocalSingleTimeUnit
from .schema import LookupData
from .schema import LookupTransform
from .schema import Mark
from .schema import MarkConfig
from .schema import MarkDef
from .schema import MarkPropFieldDefWithCondition
from .schema import MarkPropValueDefWithCondition
from .schema import MultiSelection
from .schema import MultiSelectionConfig
from .schema import NamedData
from .schema import NiceTime
from .schema import NotFilter
from .schema import OneOfFilter
from .schema import OrFilter
from .schema import OrderFieldDef
from .schema import Orient
from .schema import PositionFieldDef
from .schema import RangeConfig
from .schema import RangeFilter
from .schema import Repeat
from .schema import RepeatRef
from .schema import RepeatSpec
from .schema import Resolve
from .schema import ResolveMode
from .schema import Scale
from .schema import ScaleConfig
from .schema import ScaleResolveMap
from .schema import ScaleType
from .schema import SchemeParams
from .schema import SelectionAnd
from .schema import SelectionConfig
from .schema import SelectionDef
from .schema import SelectionDomain
from .schema import SelectionFilter
from .schema import SelectionNot
from .schema import SelectionOr
from .schema import SelectionResolution
from .schema import SingleDefChannel
from .schema import SingleSelection
from .schema import SingleSelectionConfig
from .schema import SortField
from .schema import SortOrder
from .schema import Spec
from .schema import StackOffset
from .schema import StyleConfigIndex
from .schema import TextConfig
from .schema import TextFieldDefWithCondition
from .schema import TextValueDefWithCondition
from .schema import TickConfig
from .schema import TimeUnitTransform
from .schema import TitleOrient
from .schema import TitleParams
from .schema import TopLevelExtendedSpec
from .schema import TopLevel_FacetSpec
from .schema import TopLevel_FacetedUnitSpec
from .schema import TopLevel_HConcatSpec
from .schema import TopLevel_LayerSpec
from .schema import TopLevel_RepeatSpec
from .schema import TopLevel_VConcatSpec
from .schema import TopoDataFormat
from .schema import Transform
from .schema import Type
from .schema import UrlData
from .schema import UtcMultiTimeUnit
from .schema import UtcSingleTimeUnit
from .schema import VConcatSpec
from .schema import ValueDef
from .schema import VerticalAlign
from .schema import VgAxisConfig
from .schema import VgBinding
from .schema import VgCheckboxBinding
from .schema import VgGenericBinding
from .schema import VgMarkConfig
from .schema import VgRadioBinding
from .schema import VgRangeBinding
from .schema import VgScheme
from .schema import VgSelectBinding
from .schema import VgTitleConfig
from .schema import ViewConfig
from .channel_wrappers import FacetField
from .channel_wrappers import Field
from .channel_wrappers import MarkPropFieldWithCondition
from .channel_wrappers import OrderField
from .channel_wrappers import PositionField
from .channel_wrappers import TextFieldWithCondition
from .named_channels import Color
from .named_channels import Column
from .named_channels import Detail
from .named_channels import Opacity
from .named_channels import Order
from .named_channels import Row
from .named_channels import Shape
from .named_channels import Size
from .named_channels import Text
from .named_channels import Tooltip
from .named_channels import X
from .named_channels import X2
from .named_channels import Y
from .named_channels import Y2
from .channel_collections import Encoding
from .channel_collections import EncodingWithFacet